### ISSUE TITLE
It doesn't work together with tc_aws

### ISSUE THREAD

**Issue by janisbiz** [theatlantic/thumbor-video-engine#3]
Hi!

I am trying to set it up with tc_aws, but it always throws an error of:
```
thumbor_1    | 2020-03-20 16:32:09 thumbor:ERROR [BaseHander.finish_request] [Errno 2] No such file or directory
thumbor_1    | Traceback (most recent call last):
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 422, in inner
thumbor_1    |     future_result = future.result()
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
thumbor_1    |     return self.__get_result()
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
thumbor_1    |     result = self.fn(*self.args, **self.kwargs)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 360, in _load_results
thumbor_1    |     results = context.request.engine.read(image_extension, quality)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 169, in read
thumbor_1    |     return self.transcode(extension)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 186, in transcode
thumbor_1    |     return self.transcode_to_h264(src_file)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 378, in transcode_to_h264
thumbor_1    |     return self.run_ffmpeg(src_file, 'mp4', flags=flags, two_pass=two_pass)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 443, in run_ffmpeg
thumbor_1    |     ] + flags + ['-y', out_file])
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 483, in run_cmd
thumbor_1    |     proc = Popen(command, stdout=PIPE, stdin=PIPE, stderr=PIPE)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
thumbor_1    |     errread, errwrite)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
thumbor_1    |     raise child_exception
thumbor_1    | OSError: [Errno 2] No such file or directory
thumbor_1    | 2020-03-20 16:32:09 thumbor:WARNING Error while trying to fetch the image: [Errno 2] No such file or directory
thumbor_1    | 2020-03-20 16:32:09 tornado.access:ERROR 500 GET [path of s3 bucket] (172.24.0.8) 815.13ms
```

If I try to get still, this is the result:
```
thumbor_1    | 2020-03-20 16:46:27 tornado.access:ERROR 504 GET /[hash]/1280x800/filters:still()/[s3 path] (172.24.0.8) 422.98ms
```

So my question is - is it even supported in any kind of way?

**Comment by mrzasan** [comment]
I use it with MinIO (AWS S3 standard), `still()` filter works well , but there's something wrong with  the default  filter `watermark`.
You can cp your `TC_AWS` config here for discussion.😀 
Here is my problem #2 . Maybe you can also give me some suggestions

**Comment by janisbiz** [comment]
@mrzasan I am not that far yet, but yes - I have a plans to do something similar. My TC_AWS config is as follows (replacing sensitive data):
```
LOADER = "tc_aws.loaders.presigning_loader"
RESULT_STORAGE = "tc_aws.result_storages.s3_storage"

TC_AWS_REGION="[s3 region]"

TC_AWS_LOADER_BUCKET="[s3 bucket]"
TC_AWS_LOADER_ROOT_PATH=""

TC_AWS_ENABLE_HTTP_LOADER=False
TC_AWS_ALLOWED_BUCKETS=False

TC_AWS_RESULT_STORAGE_BUCKET="[s3 bucket]"
TC_AWS_RESULT_STORAGE_ROOT_PATH="result-storage/"
TC_AWS_MAX_RETRY=0

TC_AWS_STORE_METADATA=False
```

**Comment by fdintino** [comment]
I'm not going to be able to respond to this issue today (maybe tomorrow) but I wanted to let you know that we (at The Atlantic) are using this package with tc_aws.

**Comment by mrzasan** [comment]
> @mrzasan I am not that far yet, but yes - I have a plans to do something similar. My TC_AWS config is as follows (replacing sensitive data):
> 
> ```
> LOADER = "tc_aws.loaders.presigning_loader"
> RESULT_STORAGE = "tc_aws.result_storages.s3_storage"
> 
> TC_AWS_REGION="[s3 region]"
> 
> TC_AWS_LOADER_BUCKET="[s3 bucket]"
> TC_AWS_LOADER_ROOT_PATH=""
> 
> TC_AWS_ENABLE_HTTP_LOADER=False
> TC_AWS_ALLOWED_BUCKETS=False
> 
> TC_AWS_RESULT_STORAGE_BUCKET="[s3 bucket]"
> TC_AWS_RESULT_STORAGE_ROOT_PATH="result-storage/"
> TC_AWS_MAX_RETRY=0
> 
> TC_AWS_STORE_METADATA=False
> ```

make sure  if the field  `TC_AWS_ENDPOINT` was exactly configured

**Comment by janisbiz** [comment]
@mrzasan still the same. Which version you are using?
```
thumbor --version
Thumbor v6.7.5 (9-Mar-2020)
```

**Comment by mrzasan** [comment]
> @mrzasan still the same. Which version you are using?
> 
> ```
> thumbor --version
> Thumbor v6.7.5 (9-Mar-2020)
> ```

Iv tried both v6.7.0 and v6.7.5  `still()` filter goes well.

**Comment by janisbiz** [comment]
@mrzasan I updated my comment with S3 endpoint. Mby there is a mistake?

**Comment by mrzasan** [comment]
> @mrzasan I updated my comment with S3 endpoint. Mby there is a mistake?

mb yes , but i can't confirm it, here is my tc_aws config 
![image](https://user-images.githubusercontent.com/2859944/77193553-6a4ce480-6b19-11ea-81cd-024c7757d414.png)

**Comment by janisbiz** [comment]
> > @mrzasan I updated my comment with S3 endpoint. Mby there is a mistake?
> 
> mb yes , but i can't confirm it, here is my tc_aws config
> ![image](https://user-images.githubusercontent.com/2859944/77193553-6a4ce480-6b19-11ea-81cd-024c7757d414.png)

I see that you have something custom there. The thing is that images are working properly w/o any issues, so I guess endpoint is right for me.

**Comment by janisbiz** [comment]
I have just tried same config, but with thumbor file storage - same errors. Images are working fine, but I cannot do anything with videos.

I really have no clue, why it somehow doesn't work for me.

**Comment by janisbiz** [comment]
Additional info which could be helpful:
```
ffmpeg
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
```

About pip:
```
pip list
asn1crypto (0.24.0)
backports-abc (0.5)
boto3 (1.12.26)
botocore (1.15.26)
cryptography (2.1.4)
derpconf (0.8.3)
docutils (0.15.2)
enum34 (1.1.6)
futures (3.3.0)
idna (2.6)
ipaddress (1.0.17)
jmespath (0.9.5)
keyring (10.6.0)
keyrings.alt (3.0)
libthumbor (1.3.2)
Pillow (6.2.2)
pip (9.0.1)
pycrypto (2.6.1)
pycurl (7.43.0.5)
pygobject (3.26.1)
python-dateutil (2.8.1)
pytz (2019.3)
pyxdg (0.25)
s3transfer (0.3.3)
SecretStorage (2.3.1)
setuptools (39.0.1)
singledispatch (3.4.0.3)
six (1.11.0)
statsd (3.3.0)
tc-aws (6.2.15)
thumbor (6.7.5)
thumbor-video-engine (1.0.2)
tornado (5.1.1)
tornado-botocore (1.5.0)
urllib3 (1.25.8)
webcolors (1.10)
wheel (0.30.0)
```

**Comment by mrzasan** [comment]
> I have just tried same config, but with thumbor file storage - same errors. Images are working fine, but I cannot do anything with videos.
> 
> I really have no clue, why it somehow doesn't work for me.

Any logs?

**Comment by janisbiz** [comment]
Basiacally - same thing:
```
thumbor_1    | 2020-03-21 10:39:02 thumbor:ERROR ERROR: Traceback (most recent call last):
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 153, in get_image
thumbor_1    |     self.context.request.image_url
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1133, in run
thumbor_1    |     value = future.result()
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
thumbor_1    |     raise_exc_info(self._exc_info)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1147, in run
thumbor_1    |     yielded = self.gen.send(value)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 629, in _fetch
thumbor_1    |     self.context.request.engine.load(fetch_result.buffer, extension)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/video.py", line 96, in load
thumbor_1    |     src_file, 'png', ['-ss', still_frame_pos, '-frames:v', '1'])
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 443, in run_ffmpeg
thumbor_1    |     ] + flags + ['-y', out_file])
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 483, in run_cmd
thumbor_1    |     proc = Popen(command, stdout=PIPE, stdin=PIPE, stderr=PIPE)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
thumbor_1    |     errread, errwrite)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
thumbor_1    |     raise child_exception
thumbor_1    | OSError: [Errno 2] No such file or directory
thumbor_1    | 
thumbor_1    | 2020-03-21 10:39:02 thumbor:ERROR [BaseHandler] get_image failed for url `uploads/video.mp4`. error: `[Errno 2] No such file or directory`
thumbor_1    | 2020-03-21 10:39:02 tornado.access:ERROR 500 GET /EzjieU1sae1WDA2LOC-g0VjI1Hc=/1280x800/filters:still()/uploads/video.mp4 (172.24.0.8) 10.64ms
```

**Comment by mrzasan** [comment]
> Basiacally - same thing:
> 
> ```
> thumbor_1    | 2020-03-21 10:39:02 thumbor:ERROR ERROR: Traceback (most recent call last):
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 153, in get_image
> thumbor_1    |     self.context.request.image_url
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1133, in run
> thumbor_1    |     value = future.result()
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
> thumbor_1    |     raise_exc_info(self._exc_info)
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1147, in run
> thumbor_1    |     yielded = self.gen.send(value)
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 629, in _fetch
> thumbor_1    |     self.context.request.engine.load(fetch_result.buffer, extension)
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/video.py", line 96, in load
> thumbor_1    |     src_file, 'png', ['-ss', still_frame_pos, '-frames:v', '1'])
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 443, in run_ffmpeg
> thumbor_1    |     ] + flags + ['-y', out_file])
> thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 483, in run_cmd
> thumbor_1    |     proc = Popen(command, stdout=PIPE, stdin=PIPE, stderr=PIPE)
> thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
> thumbor_1    |     errread, errwrite)
> thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
> thumbor_1    |     raise child_exception
> thumbor_1    | OSError: [Errno 2] No such file or directory
> thumbor_1    | 
> thumbor_1    | 2020-03-21 10:39:02 thumbor:ERROR [BaseHandler] get_image failed for url `uploads/video.mp4`. error: `[Errno 2] No such file or directory`
> thumbor_1    | 2020-03-21 10:39:02 tornado.access:ERROR 500 GET /EzjieU1sae1WDA2LOC-g0VjI1Hc=/1280x800/filters:still()/uploads/video.mp4 (172.24.0.8) 10.64ms
> ```

Have you tried `unsafe` model， and make sure the file  `uploads/video.mp4` can be accessed

**Comment by janisbiz** [comment]
Same thing.

```
thumbor_1    | 2020-03-21 10:51:16 thumbor:ERROR ERROR: Traceback (most recent call last):
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 153, in get_image
thumbor_1    |     self.context.request.image_url
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1133, in run
thumbor_1    |     value = future.result()
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 261, in result
thumbor_1    |     raise_exc_info(self._exc_info)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1147, in run
thumbor_1    |     yielded = self.gen.send(value)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 629, in _fetch
thumbor_1    |     self.context.request.engine.load(fetch_result.buffer, extension)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/video.py", line 96, in load
thumbor_1    |     src_file, 'png', ['-ss', still_frame_pos, '-frames:v', '1'])
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 443, in run_ffmpeg
thumbor_1    |     ] + flags + ['-y', out_file])
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 483, in run_cmd
thumbor_1    |     proc = Popen(command, stdout=PIPE, stdin=PIPE, stderr=PIPE)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
thumbor_1    |     errread, errwrite)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
thumbor_1    |     raise child_exception
thumbor_1    | OSError: [Errno 2] No such file or directory
thumbor_1    | 
thumbor_1    | 2020-03-21 10:51:16 thumbor:ERROR [BaseHandler] get_image failed for url `uploads/video.mp4`. error: `[Errno 2] No such file or directory`
thumbor_1    | 2020-03-21 10:51:16 tornado.access:ERROR 500 GET /unsafe/1280x800/filters:still()/uploads/video.mp4 (172.24.0.8) 8.95ms
```

And I can access it directly under `/uploads/video.mp4` by using nginx.
Config for file loader:
```
LOADER = 'thumbor.loaders.file_loader'
FILE_LOADER_ROOT_PATH = '/var/www/public/'
```

**Comment by janisbiz** [comment]
These are the logs with unsafe & debug enabled:
```
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG METRICS: inc: response.count:1
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG METRICS: inc: storage.miss:1
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG Setting engine to thumbor_video_engine.engines.ffmpeg (extension .mp4)
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG creating tempfile for uploads/video.mp4 in /tmp/thumbor/storage/7b/800985ee0ac4887c4a4fcc444842486b2df165.5e2e3fae902e4b368db557304339fb36...
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG moving tempfile /tmp/thumbor/storage/7b/800985ee0ac4887c4a4fcc444842486b2df165.5e2e3fae902e4b368db557304339fb36 to /tmp/thumbor/storage/7b/800985ee0ac4887c4a4fcc444842486b2df165...
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG Stored crypto at /tmp/thumbor/storage/7b/800985ee0ac4887c4a4fcc444842486b2df165.txt (security key: [key])
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG No image format specified. Retrieving from the image extension: .mp4.
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG Content Type of video/mp4 detected.
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG Running `/usr/local/bin/ffmpeg -hide_banner -i /tmp/tmpkOGtTN.mp4 -c:v libx264 -an -pix_fmt yuv420p -movflags faststart -f mp4 -y /tmp/tmphtUxUQ.mp4`
thumbor_1    | 2020-03-21 11:38:11 thumbor:ERROR [BaseHander.finish_request] [Errno 2] No such file or directory
thumbor_1    | Traceback (most recent call last):
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 422, in inner
thumbor_1    |     future_result = future.result()
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 455, in result
thumbor_1    |     return self.__get_result()
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 63, in run
thumbor_1    |     result = self.fn(*self.args, **self.kwargs)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 360, in _load_results
thumbor_1    |     results = context.request.engine.read(image_extension, quality)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 169, in read
thumbor_1    |     return self.transcode(extension)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 186, in transcode
thumbor_1    |     return self.transcode_to_h264(src_file)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 378, in transcode_to_h264
thumbor_1    |     return self.run_ffmpeg(src_file, 'mp4', flags=flags, two_pass=two_pass)
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 443, in run_ffmpeg
thumbor_1    |     ] + flags + ['-y', out_file])
thumbor_1    |   File "/usr/local/lib/python2.7/dist-packages/thumbor_video_engine/engines/ffmpeg.py", line 483, in run_cmd
thumbor_1    |     proc = Popen(command, stdout=PIPE, stdin=PIPE, stderr=PIPE)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
thumbor_1    |     errread, errwrite)
thumbor_1    |   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
thumbor_1    |     raise child_exception
thumbor_1    | OSError: [Errno 2] No such file or directory
thumbor_1    | 2020-03-21 11:38:11 thumbor:WARNING Error while trying to fetch the image: [Errno 2] No such file or directory
thumbor_1    | 2020-03-21 11:38:11 tornado.access:ERROR 500 GET /unsafe/uploads/video.mp4 (172.24.0.8) 101.56ms
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG METRICS: timing: response.time:101
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG METRICS: timing: response.time.500:101
thumbor_1    | 2020-03-21 11:38:11 thumbor:DEBUG METRICS: inc: response.status.500:1
```

**Comment by fdintino** [comment]
Is ffmpeg in `/usr/bin`? Perhaps try putting in your settings

```python
FFMPEG_PATH = '/usr/bin/ffmpeg'
```

**Comment by janisbiz** [comment]
Hi @fdintino, yes, it is in `/usr/bin`:
```
which ffmpeg
/usr/bin/ffmpeg
```

but by adding the above path to `FFMPEG_PATH` it works. Would recommend adding some logging in this case. Thanks for helping out with this. :)
